version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: db_doc_x_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"


